name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        ruby: [ '2.7' ]

    steps:
    - uses: actions/checkout@v2

    - name: Set up Ruby ${{ matrix.ruby }}
      uses: actions/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}

    - name: Build App
      run: |
        gem install bundler
        bundle install --jobs 4 --retry 3
    - name: Run Tests
      env:
        RAILS_ENV: test
      run: |
        bundle exec rspec
